name: sortpics
channels:
  - default
  - conda-forge
dependencies:
  - python>=3.6
  - pillow
  - tqdm
  - pytest
  - pytest-xdist
  - pytest-cov
  - pre-commit
  - black
  - flake8
  - codecov
  - pylint
  - pip
  - twine
  - pip:
    - -r file:requirements.txt
